[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "GlitchApotamus"
name = "DiscordHook"
description = "Sends a discord webhook on certain game events. In the furture, this will be expanded to include more events such as serving details per level."
websiteUrl = "https://github.com/GlitchApotamus/DiscordHook/"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Zehs.REPOLib = "2.0.1"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../../Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/glitchapotamus.discordhook.dll"
target = "BepInEx/plugins/DiscordHook/glitchapotamus.discordhook.dll"

[[build.copy]]
source = "../LICENSE"
target = "LICENSE"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
communities = [ "repo" ]
[publish.categories]
repo = [ "mods", "misc", "serverside", "clientside" ]
